[package]
name = "rust-playground"
version = "0.1.0"
authors = ["lbt05"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.4"
